name = "worker-proxy"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat", "nodejs_als"]
compatibility_date = "2025-06-04"
minify = true
send_metrics = false

[placement]
mode = "smart"

[dev]
port = 7860
