name: Format

on:
  push:
    paths:
      - .github/workflows/formatter.yml
      - bun.lockb
      - '**.ts*'
      - '**.json'

permissions:
  contents: write

jobs:
  format:
    uses: winstxnhdw/actions/.github/workflows/format-bun.yml@main
