name: Format

on:
  push:
    paths:
      - .github/workflows/formatter.yml
      - biome.json
      - package.json
      - bun.lockb
      - src/*

permissions:
  contents: write


jobs:
  format:
    uses: winstxnhdw/actions/.github/workflows/format-bun.yml@main
