name: Test

on:
  pull_request:
    types: opened
  push:
    paths:
      - .github/workflows/test.yml
      - .eslintrc
      - .eslintignore
      - tsconfig.json
      - package.json
      - bun.lockb
      - '*.ts'

jobs:
  test:
    uses: winstxnhdw/actions/.github/workflows/bun.yml@main
    with:
      disable-build: true
