name: Test

on:
  pull_request_target:
    types: [opened, reopened]
  pull_request:
    paths:
      - .github/workflows/main.yml
      - .eslintrc
      - .eslintignore
      - tsconfig.json
      - package.json
      - bun.lockb
      - '*.ts'
  push:
    paths:
      - .github/workflows/main.yml
      - .eslintrc
      - .eslintignore
      - tsconfig.json
      - package.json
      - bun.lockb
      - src/*

jobs:
  test:
    uses: winstxnhdw/actions/.github/workflows/bun.yml@main
    with:
      disable-build: true
