name: Test

on:
  pull_request:
    types: opened
  push:
    paths:
      - .github/workflows/test.yml
      - .eslintrc
      - .eslintignore
      - tsconfig.json
      - package.json
      - bun.lockb
      - '*.ts'

jobs:
  bun:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.2
        with:
          show-progress: false

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .
