name: Test

on:
  pull_request:
    types: opened
  push:
    paths:
      - .github/workflows/main.yml
      - biome.json
      - tsconfig.json
      - package.json
      - bun.lockb
      - src/**

jobs:
  bun:
    uses: winstxnhdw/actions/.github/workflows/bun.yml@main
    with:
      disable-formatter: true
      disable-test: true
      disable-build: true
