name: E2E Test

on:
  workflow_dispatch:
  workflow_run:
    workflows: Deploy
    branches: main
    types: completed
  push:
    paths: .github/workflows/test.yml

jobs:
  test:
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    env:
      WORKER_ENDPOINT: ${{ secrets.WORKER_ENDPOINT }}

    steps:
      - name: cURL Worker
        run: |
          echo "RESPONSE=\
            $(curl -s $WORKER_ENDPOINT/get/default?endpoint=https%3A%2F%2Fhosted.winst.in%2Ftest.txt)" >> $GITHUB_ENV

      - name: Test Success
        env:
          RESPONSE: ${{ env.RESPONSE }}
        run: |
          [ "$RESPONSE" = "The quick brown fox jumps over the lazy dog." ]

      - name: Test Failure
        env:
          RESPONSE: ${{ env.RESPONSE }}
        run: |
          [ ! "$RESPONSE" = "This should return false." ]
